Repository bis-med-it/pysdmx, pull requests merged in 2025-07, with the labels that each got.

#350 Failure to read SDMX-ML 2.1 Generic message when Obs has no ObsValue
  src/pysdmx/io/xml/sdmx21/reader/generic.py
  tests/io/xml/sdmx21/reader/samples/gen_all.xml
  tests/io/xml/sdmx21/reader/samples/gen_ser.xml
Labels: bug

#356 CoreRepresentation writes TextFormat instead of the expected EnumerationFormat
  src/pysdmx/io/xml/__structure_aux_writer.py
  tests/io/xml/sdmx21/writer/samples/enum_format.xml
  tests/io/xml/sdmx21/writer/test_structures_writing.py
Labels: bug

#359 Raise an error when trying to write a DataStructureDefinition with more than one measure in SDMX-ML 2.1
  src/pysdmx/io/xml/__structure_aux_writer.py
  tests/io/xml/sdmx21/writer/test_structures_writing.py
Labels: enhancement

#338 Enhance documentation on io package and SDMX-VTL interconnection
  docs/_static/data.xml
  docs/_static/structures.xml
  docs/_static/vtl_ts.xml
  docs/api/io.rst
  docs/api/io/general_reader.rst
  docs/api/io/general_writer.rst
  docs/api/io/pandas_ds.rst
  docs/api/io/sdmx_csv.rst
  docs/api/io/sdmx_ml.rst
  docs/api/model.rst
  docs/api/model/dataflow.rst
  docs/api/model/dataset.rst
  docs/api/model/message.rst
  docs/api/model/vtl.rst
  docs/howto/data_rw.rst
  docs/howto/generate_ts.rst
  docs/howto/io_data.rst
  docs/howto/io_structure.rst
  docs/howto/toolkit/general.rst
  docs/howto/toolkit/vtl_toolkit.rst
  docs/howto/vtl.rst
  docs/howto/vtl_handling.rst
  docs/index.rst
  docs/start.rst
  src/pysdmx/io/input_processor.py
  src/pysdmx/io/pd.py
  src/pysdmx/io/reader.py
  src/pysdmx/io/writer.py
  src/pysdmx/io/xml/sdmx21/writer/structure.py
  src/pysdmx/io/xml/sdmx30/writer/structure.py
  src/pysdmx/model/__base.py
  src/pysdmx/model/dataset.py
  src/pysdmx/model/message.py
  tests/io/test_general_writer.py
  tests/model/test_dataflow_ref.py
Labels: documentation

#357 Roundtrip reading SDMX-ML 2.1 and writing SDMX-ML 3.0 raises errors due to Agency URNs
  src/pysdmx/io/xml/__structure_aux_writer.py
  tests/io/samples/datastructure_descendants.xml
  tests/io/xml/sdmx21/writer/samples/bis_der.xml
  tests/io/xml/sdmx21/writer/samples/del_groups.xml
  tests/io/xml/sdmx30/writer/samples/bis_der_agencies.xml
  tests/io/xml/sdmx30/writer/test_structures_writing.py
Labels: bug

#361 Allow use of ID in Header
  src/pysdmx/model/message.py
  tests/model/test_message.py
Labels: enhancement
